config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  get "stopwatch" =>"stopwatch#index"

  resources :projects do
    resources :time_entries
  end

  resources :pros
  resources :projects
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :time_entries, dependent: :destroy

end

app/models/time_entry.rb
class TimeEntry < ApplicationRecord
  belongs_to :project
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_time_entries, only: [:show]


  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @projects.each do |project|
      worked_hours = 0
      @time_entries = TimeEntry.where(Project_id: project.id)
      @time_entries.each do |entry|
        worked_hours += entry.number_of_hours
      end
      project.update_attribute(:worked_hours, worked_hours)
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_time_entries
      if @project
        @time_entries = TimeEntry.where(Project_id: @project.id)
        hours_worked = 0
        @time_entries.each do |entry|
            hours_worked += entry.number_of_hours
        end
        @project.update_attribute(:worked_hours, hours_worked)
      end

    end
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :total_hours_to_finish, :worked_hours).merge(user_id: current_user.id)
    end
end

app/controllers/stopwatch_controller.rb
class StopwatchController < ApplicationController
   def index
      if current_user
        @projects = current_user.projects
      end
   end
end

app/controllers/time_entries_controller.rb
class TimeEntriesController < ApplicationController
  before_action :set_time_entry, only: [:show, :edit, :update, :destroy]

  # GET /time_entries
  # GET /time_entries.json
  def index
    @time_entries = TimeEntry.all
  end

  # GET /time_entries/1
  # GET /time_entries/1.json
  def show
  end

  # GET /time_entries/new
  def new
    @time_entry = TimeEntry.new
  end

  # GET /time_entries/1/edit
  def edit
  end

  # POST /time_entries
  # POST /time_entries.json
  def create
    @time_entry = TimeEntry.new(time_entry_params)

    respond_to do |format|
      if @time_entry.save
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully created.' }
        format.json { render :show, status: :created, location: @time_entry }
      else
        format.html { render :new }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_entries/1
  # PATCH/PUT /time_entries/1.json
  def update
    respond_to do |format|
      if @time_entry.update(time_entry_params)
        format.html { redirect_to @time_entry, notice: 'Time entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_entry }
      else
        format.html { render :edit }
        format.json { render json: @time_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_entries/1
  # DELETE /time_entries/1.json
  def destroy
    @time_entry.destroy
    respond_to do |format|
      format.html { redirect_to project_time_entries_path, notice: 'Time entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_entry
      @time_entry = TimeEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_entry_params
      params.require(:time_entry).permit(:number_of_hours, :date, :description, :Project_id)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/stopwatch_helper.rb
module StopwatchHelper
end

app/helpers/time_entries_helper.rb
module TimeEntriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= yield :head %>
    <title>Jirafaestudia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= notice %></p>

<header class="navbar  navbar-inverse">
  <div class="container" id="navbar">
    <div class="row">
      <div id="sidebar" class="col-xs-3">
        <ul class="nav navbar-nav">
        <item><%= link_to "Home", root_path %></item>
        <% if signed_in? %>
        <item><%=link_to "Users", users_path %></item>
        <item><%=link_to "Projects", projects_path %></item>
        <% end %>
        <item><%=link_to "Stopwatch", stopwatch_path,  data: { turbolinks: 'false' } %></item>
        </ul>
    </div>
    </div>
    <div class="container">
      <ul class="nav navbar-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </ul>

    </div>
  </div>
</header>

  <body>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :total_hours_to_finish %>
    <%= f.number_field :total_hours_to_finish %>
  </div>

  <div class="field">
    <%= f.label :worked_hours %>
    <%= f.number_field :worked_hours %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Total hours to finish</th>
      <th>Worked hours</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= project.total_hours_to_finish %></td>
        <td><%= project.worked_hours %></td>
        <td><%= project.user %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Total hours to finish:</strong>
  <%= @project.total_hours_to_finish %>
</p>

<p>
  <strong>Worked hours:</strong>
  <%= @project.worked_hours %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/stopwatch/index.html.erb
  <body id ="stopwatch" data-no-turbolink>

    <div class = "container">
      <div class = "stopwatch_main">
      <h1>Hello User! </h1>
      <h1><time>00:00:00</time></h1>
      <button class = "btn btn-success start">Start</button>
      <button class = "btn btn-warning stop">Stop</button>
      <button class = "btn btn-primary reset">Reset</button>
      <button class = "btn btn-primary archive">Archive</button>
      <select class ="s_project">Project
         <% if @projects %>
         <% @projects.each do |project| %>
         <option value=project.name><%=project.name%></option>
         <% end %>
         <% end %>
      </select>

  </div>
  <div class = "clockConfig">
  How long should your pomodoro be? (min)--doesnt work--:
  <input class = "timePomodoro" type="number" name="timePomodoro" min="0">
  </div>
</br>

  <div class = "ChartEntries">

    <label for="switch">Monthly View?</label>
    <input type="checkbox" name="switch_to_month" id="switch_to_month">
    <br>

  </div>
  </div>

  </body>

app/views/time_entries/_form.html.erb
<%= form_for(time_entry) do |f| %>
  <% if time_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_entry.errors.count, "error") %> prohibited this time_entry from being saved:</h2>

      <ul>
      <% time_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number_of_hours %>
    <%= f.number_field :number_of_hours %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_select :date %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%= f.label :Project_id %>
    <%= f.text_field :Project_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/time_entries/edit.html.erb
<h1>Editing Time Entry</h1>

<%= render 'form', time_entry: @time_entry %>

<%= link_to 'Show', @time_entry %> |
<%= link_to 'Back', time_entries_path %>

app/views/time_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Entries</h1>

<table>
  <thead>
    <tr>
      <th>Number of hours</th>
      <th>Date</th>
      <th>Description</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_entries.each do |time_entry| %>
      <tr>
        <td><%= time_entry.number_of_hours %></td>
        <td><%= time_entry.date %></td>
        <td><%= time_entry.description %></td>
        <td><%= time_entry.Project %></td>
        <td><%= link_to 'Show', project_time_entry_path(time_entry.Project.id, time_entry) %></td>
        <td><%= link_to 'Edit', [:edit, time_entry.Project, time_entry ] %></td>
        <td><%= link_to 'Destroy', [ time_entry.Project, time_entry ],method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Entry', new_project_time_entry_path %>

app/views/time_entries/new.html.erb
<h1>New Time Entry</h1>

<%= render 'form', time_entry: @time_entry %>

<%= link_to 'Back', time_entries_path %>

app/views/time_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number of hours:</strong>
  <%= @time_entry.number_of_hours %>
</p>

<p>
  <strong>Date:</strong>
  <%= @time_entry.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @time_entry.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @time_entry.Project %>
</p>

<%= link_to 'Edit', edit_time_entry_path(@time_entry) %> |
<%= link_to 'Back', time_entries_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Welcome to Super Time Manager 24</h1>
<p>Find me in app/views/welcome/index.html.erb</p>